# SETTINGS
[notebook]
dir = "Download" # same as "$HOME/notebook"

[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "TheCrow95T"


# GROUP OVERRIDES
[group.standup]
paths = ["notes/StandUp"]

[group.standup.note]
filename = "{{format-date now}}"
extension = "md"
template = "standup.md"

[group.daily]
paths = ["Journal"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.learn]
paths = ["notes/Learn"]

[group.learn.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "learn.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# list notes for editing
ls = "zk edit --interactive"

# search notes by tags
t = "zk edit --interactive --tag $argv"

# new note
ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Ideas" --title $argv'
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Journal"'
learn = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Learn" --group learn --title $argv'
stand = 'zk new --no-input "$ZK_NOTEBOOK_DIR/StandUp"'

# list
ls-ne = "zk edit $ZK_NOTEBOOK_DIR/Ideas --sort created- --interactive"
ls-stand = 'zk edit "$ZK_NOTEBOOK_DIR/StandUp" --sort created- --interactive'
ls-daily = "zk edit $ZK_NOTEBOOK_DIR/Journal --sort created- --interactive"
ls-learn = "zk edit $ZK_NOTEBOOK_DIR/Ideas --sort created- --interactive"

# update zk notes
update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
